orm:
  auto_generate_proxy_classes: true
  naming_strategy: doctrine.orm.naming_strategy.underscore
  auto_mapping: true
  mappings:
    CookingPaymentsBundle:
      is_bundle: false
      type: attributes
      dir: '%kernel.project_dir%/src/Entity'
      prefix: 'Greendot\EshopBundle\Entity'
      alias: Greendot\EshopBundle